stages:
- test
- sonar_pr
- sonar

auto_test:
  stage: test
  script:
  - chmod +x ci/auto_test.sh
  - ci/auto_test.sh

sonar_preview:
  stage: sonar_pr
  script:
  - chmod +x ci/sonar_preview.sh
  - ci/sonar_preview.sh

sonar_analyze:
  stage: sonar
  script:
  - chmod +x ci/sonar_analyze.sh
  - ci/sonar_analyze.sh
