spring:
  datasource:
    url: jdbc:mysql://10.20.0.94:3306/base?serverTimezone=UTC&useTimezone=true&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&useSSL=false&allowMultiQueries=true
    username: dev1
    password: K(adjJIaf7RT
  redis:
    cluster:
      nodes: 10.20.0.85:6379

jasypt:
  encryptor:
    password: dop-sunvalley

dop:
  idgen:
    redis:
      cluster:
        nodes: 10.20.0.85:6379
      timeout: 1000MS
  ribbon:
    filter:
      metadata:
        prior-ip-pattern:
        - 10.20.0.*

## rocketMq
rocketmq:
  name-server: 10.20.0.83:9876
  producer.group: ${spring.application.name}

logging:
  level:
    com.sunvalley: debug
    mvc.api: debug
    github.sjroom.feign.common.FeignServiceFacade: debug
